"""
Complete HIL Bridge & System Isolation Source FilesFile 1: src/am_machine_description/mujoco/scripts/mujoco_shm_bridge.pyThis script uses standard Python mmap bindings to connect directly to the active POSIX shared memory block (/am_mujoco_shm). Running at a native 1kHz cycle rate inside the MuJoCo engine, it captures simulated sensor feeds, writes them into the shared RAM block, and instantaneously reads back target trajectory updates from your real-time control loops.
"""
#!/usr/bin/env python3
import os
import mmap
import time
import struct
import numpy as np
import mujoco
import mujoco.viewer

SHM_NAME = "/dev/shm/am_mujoco_shm"
# Data layout format matching C++ struct boundaries: 
# 6 doubles (positions), 6 doubles (velocities), 6 doubles (commands), 256 floats (sensor stream), 1 bool (exception_trigger)
# Struct format token string: '6d 6d 6d 256f ?'
STRUCT_FORMAT = '6d6d6d256f?'
STRUCT_SIZE = struct.calcsize(STRUCT_FORMAT)

class MujocoShmBridge:
    def __init__(self, xml_path):
        print(f"[MUJOCO_BRIDGE] Loading physical model twin: {xml_path}")
        self.model = mujoco.MjModel.from_xml_path(xml_path)
        self.data = mujoco.MjData(self.model)
        
        # 1. Connect to or allocate the low-latency POSIX Shared Memory segment
        if not os.path.exists(SHM_NAME):
            with open(SHM_NAME, "wb") as f:
                f.write(b"\x00" * STRUCT_SIZE)
                
        self.shm_file = open(SHM_NAME, "r+b")
        self.shm_mmap = mmap.mmap(self.shm_file.fileno(), STRUCT_SIZE)
        print("[MUJOCO_BRIDGE] Zero-copy Shared Memory pipeline linked successfully.")

    def run_bridge(self):
        print("[MUJOCO_BRIDGE] Spinning up 1kHz Hardware-In-The-Loop (HIL) simulation runner...")
        with mujoco.viewer.launch_passive(self.model, self.data) as viewer:
            while viewer.is_running():
                step_start = time.time()
                
                # 2. Extract current simulation metrics from MuJoCo registers
                current_qpos = self.data.qpos[:6].tolist()
                current_qvel = self.data.qvel[:6].tolist()
                
                # Mock a 256-element sensor data block representing melt-pool thermal inspection signatures
                sim_sensor_stream = np.random.normal(0.5, 0.02, 256).astype(np.float32).tolist()
                
                # 3. Read back latest targeted servo references generated by the PREEMPT_RT core loop
                self.shm_mmap.seek(0)
                shm_raw_data = self.shm_mmap.read(STRUCT_SIZE)
                unpacked_data = struct.unpack(STRUCT_FORMAT, shm_raw_data)
                
                rt_commands = unpacked_data[12:18] # Extracting the 6 double commands elements
                
                # 4. Inject real-time trajectory updates directly into MuJoCo actuator channels
                self.data.ctrl[:6] = rt_commands
                
                # 5. Advance the internal physics equations
                mujoco.mj_step(self.model, self.data)
                viewer.sync()
                
                # 6. Stream current tracking positions and sensor profiles back to the shared memory block
                packed_payload = struct.pack(
                    STRUCT_FORMAT,
                    *current_qpos,
                    *current_qvel,
                    *rt_commands,  # Loop back commands for state tracking verification
                    *sim_sensor_stream,
                    False          # Exception trigger flag status
                )
                self.shm_mmap.seek(0)
                self.shm_mmap.write(packed_payload)
                self.shm_mmap.flush()
                
                # Maintain uniform 1kHz control rhythm loops (1ms)
                time_elapsed = time.time() - step_start
                if time_elapsed < 0.001:
                    time.sleep(0.001 - time_elapsed)

    def close(self):
        self.shm_mmap.close()
        self.shm_file.close()

if __name__ == "__main__":
    xml_scene_path = os.path.join(os.path.dirname(__file__), "../am_scene.xml")
    bridge = MujocoShmBridge(xml_scene_path)
    try:
        bridge.run_bridge()
    except KeyboardInterrupt:
        print("\n[MUJOCO_BRIDGE] Graceful shutdown initialized.")
    finally:
        bridge.close()
      
